version: "3.4"

services:
  newbe.claptrap.ticketing.web:
    image: newbe-claptrap-ticketing-web
    restart: always
    ports:
      - "10080:80"
    environment:
      ASPNETCORE_URLS: "http://+:80"
    depends_on:
      - newbe.claptrap.ticketing.backendserver
    environment:
      Claptrap__Orleans__Hostname: newbe.claptrap.ticketing.backendserver
      Claptrap__Orleans__Clustering__ConsulUrl: "http://consulnode1:8500"
      Ticketing__ApiBaseUrl: "http://127.0.0.1"
      Ticketing__SiteFooterHtml: "<div class=\"my-5 pt-5 text-muted text-center text-small\"></div>"

  newbe.claptrap.ticketing.backendserver:
    image: newbe-claptrap-ticketing-backendserver
    restart: always
    ports:
      - "11111"
      - "30000"
    environment:
      Claptrap__Orleans__Hostname: newbe.claptrap.ticketing.backendserver
      Claptrap__Orleans__Clustering__ConsulUrl: "http://consulnode1:8500"

  consulnode1:
    image: bitnami/consul
    restart: always
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consulnode1
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'

  consulnode2:
    image: bitnami/consul
    restart: always
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consulnode1
      - CONSUL_ENABLE_UI=false

  consulnode3:
    image: bitnami/consul
    restart: always
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consulnode1
      - CONSUL_ENABLE_UI=false