//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newbe.Claptrap.Ticketing.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Services_StationResources_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Services_StationResources_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newbe.Claptrap.Ticketing.Web.Resources.Services.StationResources.zh", typeof(Services_StationResources_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 澳门.
        /// </summary>
        internal static string ao_men {
            get {
                return ResourceManager.GetString("ao men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 北京.
        /// </summary>
        internal static string bei_jing {
            get {
                return ResourceManager.GetString("bei jing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长春.
        /// </summary>
        internal static string chang_chun {
            get {
                return ResourceManager.GetString("chang chun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 长沙.
        /// </summary>
        internal static string chang_sha {
            get {
                return ResourceManager.GetString("chang sha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成都.
        /// </summary>
        internal static string cheng_du {
            get {
                return ResourceManager.GetString("cheng du", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重庆.
        /// </summary>
        internal static string chong_qing {
            get {
                return ResourceManager.GetString("chong qing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 福州.
        /// </summary>
        internal static string fu_zhou {
            get {
                return ResourceManager.GetString("fu zhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 广州.
        /// </summary>
        internal static string guang_zhou {
            get {
                return ResourceManager.GetString("guang zhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 贵阳.
        /// </summary>
        internal static string gui_yang {
            get {
                return ResourceManager.GetString("gui yang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 哈尔滨.
        /// </summary>
        internal static string ha_er_bin {
            get {
                return ResourceManager.GetString("ha er bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海口.
        /// </summary>
        internal static string hai_kou {
            get {
                return ResourceManager.GetString("hai kou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 杭州.
        /// </summary>
        internal static string hang_zhou {
            get {
                return ResourceManager.GetString("hang zhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合肥.
        /// </summary>
        internal static string he_fei {
            get {
                return ResourceManager.GetString("he fei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 呼和浩特.
        /// </summary>
        internal static string hu_he_hao_te {
            get {
                return ResourceManager.GetString("hu he hao te", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 济南.
        /// </summary>
        internal static string ji_nan {
            get {
                return ResourceManager.GetString("ji nan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昆明.
        /// </summary>
        internal static string kun_ming {
            get {
                return ResourceManager.GetString("kun ming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拉萨.
        /// </summary>
        internal static string la_sa {
            get {
                return ResourceManager.GetString("la sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兰州.
        /// </summary>
        internal static string lan_zhou {
            get {
                return ResourceManager.GetString("lan zhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 南昌.
        /// </summary>
        internal static string nan_chang {
            get {
                return ResourceManager.GetString("nan chang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 南京.
        /// </summary>
        internal static string nan_jing {
            get {
                return ResourceManager.GetString("nan jing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 南宁.
        /// </summary>
        internal static string nan_ning {
            get {
                return ResourceManager.GetString("nan ning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海.
        /// </summary>
        internal static string shang_hai {
            get {
                return ResourceManager.GetString("shang hai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沈阳.
        /// </summary>
        internal static string shen_yang {
            get {
                return ResourceManager.GetString("shen yang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 石家庄.
        /// </summary>
        internal static string shi_jia_zhuang {
            get {
                return ResourceManager.GetString("shi jia zhuang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 台北.
        /// </summary>
        internal static string tai_bei {
            get {
                return ResourceManager.GetString("tai bei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 太原.
        /// </summary>
        internal static string tai_yuan {
            get {
                return ResourceManager.GetString("tai yuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天津.
        /// </summary>
        internal static string tian_jin {
            get {
                return ResourceManager.GetString("tian jin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 武汉.
        /// </summary>
        internal static string wu_han {
            get {
                return ResourceManager.GetString("wu han", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乌鲁木齐.
        /// </summary>
        internal static string wu_lu_mu_qi {
            get {
                return ResourceManager.GetString("wu lu mu qi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西安.
        /// </summary>
        internal static string xi_an {
            get {
                return ResourceManager.GetString("xi an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西宁.
        /// </summary>
        internal static string xi_ning {
            get {
                return ResourceManager.GetString("xi ning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 香港.
        /// </summary>
        internal static string xiang_gang {
            get {
                return ResourceManager.GetString("xiang gang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 银川.
        /// </summary>
        internal static string yin_chuan {
            get {
                return ResourceManager.GetString("yin chuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郑州 .
        /// </summary>
        internal static string zheng_zhou {
            get {
                return ResourceManager.GetString("zheng zhou", resourceCulture);
            }
        }
    }
}
