//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newbe.Claptrap.Ticketing.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages_Index_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages_Index_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newbe.Claptrap.Ticketing.Web.Resources.Pages.Index.zh", typeof(Pages_Index_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预定.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目的地.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 座位号必须为数字.
        /// </summary>
        internal static string Invalid_seat_number {
            get {
                return ResourceManager.GetString("Invalid seat number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无车次.
        /// </summary>
        internal static string No_Trip {
            get {
                return ResourceManager.GetString("No Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 始发地.
        /// </summary>
        internal static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择与始发地不同的目的地.
        /// </summary>
        internal static string Please_select_a_different_destination_to_origin {
            get {
                return ResourceManager.GetString("Please select a different destination to origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择目的地.
        /// </summary>
        internal static string Please_select_destination {
            get {
                return ResourceManager.GetString("Please select destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择始发站.
        /// </summary>
        internal static string Please_select_origin {
            get {
                return ResourceManager.GetString("Please select origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择始发地和目的地.
        /// </summary>
        internal static string Please_select_origin_and_destination {
            get {
                return ResourceManager.GetString("Please select origin and destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入0-9999之间的座位号，或者 -1 进行随机选择.
        /// </summary>
        internal static string Please_type_a_seat_number_from_0_to_9999__or__1_for_random {
            get {
                return ResourceManager.GetString("Please type a seat number from 0 to 9999, or -1 for random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车次查询.
        /// </summary>
        internal static string Search_by_train {
            get {
                return ResourceManager.GetString("Search by train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余座位数：.
        /// </summary>
        internal static string Seat_Left_ {
            get {
                return ResourceManager.GetString("Seat Left:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共计.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 铁路路线.
        /// </summary>
        internal static string Train_Route {
            get {
                return ResourceManager.GetString("Train Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车次：.
        /// </summary>
        internal static string Trip_ {
            get {
                return ResourceManager.GetString("Trip:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车次.
        /// </summary>
        internal static string Trips {
            get {
                return ResourceManager.GetString("Trips", resourceCulture);
            }
        }
    }
}
