version: '3.4'


services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  influxdb:
    image: influxdb
    ports:
      - 19086:8086
    environment:
      INFLUXDB_DB: metricsdatabase
      INFLUXDB_ADMIN_USER: claptrap
      INFLUXDB_ADMIN_PASSWORD: claptrap

  adminer:
    image: adminer
    restart: always
    ports:
        - 58080:8080

  clustering:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: claptrap
    volumes:
        - ./clustering:/docker-entrypoint-initdb.d
  
  claptrap_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: claptrap
    volumes:
        - ./claptrap_db:/docker-entrypoint-initdb.d
      
  webapi:
    image: newb-eclaptrap-auth-webapi
    restart: always
    ports:
      - "10080:80"
    environment: 
      Claptrap__Orleans__Clustering__Invariant: MySql.Data.MySqlClient
      Claptrap__Orleans__Clustering__ConnectionString: Server=clustering;Database=claptrap_clustering;Uid=root;Pwd=claptrap;Pooling=True;
      ASPNETCORE_URLS: "http://+:80"
    depends_on: 
      - cluster_bootstrap

  cluster_bootstrap:
    image: newbe-claptrap-auth-backendserver
    restart: always
    ports:
      - "11111"
    environment: 
      Claptrap__DefaultConnectionString: Server=claptrap_db;Database=claptrap;Uid=root;Pwd=claptrap;Pooling=True;
      Claptrap__Orleans__Hostname: cluster_bootstrap
      Claptrap__Orleans__GatewayPort: 0
      Claptrap__Orleans__SiloPort: 11111
      Claptrap__Orleans__Clustering__Invariant: MySql.Data.MySqlClient
      Claptrap__Orleans__Clustering__ConnectionString: Server=clustering;Database=claptrap_clustering;Uid=root;Pwd=claptrap;Pooling=True;
    depends_on: 
      - clustering

  cluster_core:
    image: newbe-claptrap-auth-backendserver
    restart: always
    ports:
      - "11111"
    environment: 
      Claptrap__DefaultConnectionString: Server=claptrap_db;Database=claptrap;Uid=root;Pwd=claptrap;Pooling=True;
      Claptrap__Orleans__Hostname: cluster_core
      Claptrap__Orleans__GatewayPort: 0
      Claptrap__Orleans__SiloPort: 11111
      Claptrap__Orleans__Clustering__Invariant: MySql.Data.MySqlClient
      Claptrap__Orleans__Clustering__ConnectionString: Server=clustering;Database=claptrap_clustering;Uid=root;Pwd=claptrap;Pooling=True;
    depends_on: 
      - cluster_bootstrap

  cluster_gateway:
    image: newbe-claptrap-auth-backendserver
    restart: always
    ports:
      - "11111"
      - "30000"
    environment: 
      Claptrap__Orleans__Hostname: cluster_gateway
      Claptrap__Orleans__GatewayPort: 30000
      Claptrap__Orleans__SiloPort: 11111
      Claptrap__Orleans__Clustering__Invariant: MySql.Data.MySqlClient
      Claptrap__Orleans__Clustering__ConnectionString: Server=clustering;Database=claptrap_clustering;Uid=root;Pwd=claptrap;Pooling=True;
    depends_on: 
      - cluster_bootstrap

  dashboard:
    image: newbe-claptrap-auth-backendserver
    restart: always
    ports:
      - "11111"
      - "9000:9000"
    environment: 
      Claptrap__DefaultConnectionString: Server=claptrap_db;Database=claptrap;Uid=root;Pwd=claptrap;Pooling=True;
      Claptrap__Orleans__EnableDashboard: "true"
      Claptrap__Orleans__Hostname: dashboard
      Claptrap__Orleans__GatewayPort: 0
      Claptrap__Orleans__SiloPort: 11111
      Claptrap__Orleans__Clustering__Invariant: MySql.Data.MySqlClient
      Claptrap__Orleans__Clustering__ConnectionString: Server=clustering;Database=claptrap_clustering;Uid=root;Pwd=claptrap;Pooling=True;
    depends_on: 
      - cluster_bootstrap