name: Newbe.Claptrap.Ticketing build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE/src/Newbe.Claptrap.Ticketing
          dotnet restore
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/src/Newbe.Claptrap.Ticketing
          dotnet build --configuration Release --no-restore
      - name: Test
        run: |
          cd $GITHUB_WORKSPACE/src/Newbe.Claptrap.Ticketing
          dotnet test